version: '3.4'

services:
  userapi:
    ports:
      - "8080:8080"
      # - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      # - ASPNETCORE_HTTPS_PORTS=8081
      # - ASPNETCORE_URLS=https://+:443;http://+:80
      # - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      # - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes:
      - ~/.aspnet/https:/https:ro