version: '3.4'

services:
  userapi:
    image: ${DOCKER_REGISTRY-}userapi
    build:
      context: .
      dockerfile: UserApi/Dockerfile
  mysql_db:
     image: mysql:latest
     ports:
           - "3306:3306"
     environment:
            - MYSQL_ROOT_HOST=% 
            - MYSQL_ROOT_PASSWORD=Password 
  client_app:
    # image: ${DOCKER_REGISTRY-}clent_app
    build: 
      context: .
      dockerfile: clientApp/Dockerfile
    ports:
      - "3000:3000"

